language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - LC_ALL=C
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq liblzo2-dev
install:
  - "pip install -e ."
  - "pip install nose"
script: nosetests
