name: Tests

on:
    push:

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - pypy-3.6
          - pypy-3.7
        os:
          - ubuntu-latest
#          - macos-latest
#          - windows-latest
        exclude:
          - os: macos-latest
            python-version: 'pypy-3.6'
    runs-on:  ${{ matrix.os }}
    name: ${{ matrix.os }} @ ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
           if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt install liblzo2-dev
           elif [ "$RUNNER_OS" == "Windows" ]; then
              echo "$RUNNER_OS not supported"
           else
              echo "$RUNNER_OS not supported"
           fi
      - run: python setup.py install
      - run: pip install nose
      - run: nosetests --with-doctest tests/
